#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1637453069                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://1drv.ms/u/c/163ac3abe6e365ca/ESMuzlkOk5lGsBWcXWfA20MBk541TAdmWJkC566iyRCQjA?e=HVUCKM # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free, or $1/month, $5/year (USD)          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Beautiful Weather at a Glance

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Appealing Apps
your_link                                 : https://appealingapps.dev
your_city                                 : Michigan, USA
email_address                             : hello@appealingapps.dev
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : appealingapps
github_username                           : appealingapps
youtube_username                          : 
mastodon_link                             : https://mastodon.social/@appealingapps



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Designed for Apple
    description                           : Beautiful and feels native to Apple platforms. We sweat the details :)
    fontawesome_icon_name                 : mobile
    
  - title                                 : Lightning Quick
    description                           : Don't wait...get your weather as fast as possible. We use smart caching to show you your weather as fast as possible.
    fontawesome_icon_name                 : bolt

  - title                                 : Widgets
    description                           : Widgets for every size and need...and more to come!
    fontawesome_icon_name                 : wand-magic-sparkles

  - title                                 : Radar
    description                           : See the current precipitation radar and cloud cover. With a silver subscription, you can see the future!
    fontawesome_icon_name                 : radar

  - title                                 : Watch App
    description                           : Check the forecast from your wrist with our Apple Watch app. We have widgets and complication support too!
    fontawesome_icon_name                 : clock

  - title                                 : Customization Galore
    description                           : We've got customization options for every part of the app. Make it yours!
    fontawesome_icon_name                 : sliders

  - title                                 : More on the Way
    description                           : Rainy Skies is actively being developed and more features are coming!
    fontawesome_icon_name                 : plus

  - title                                 : 100% Free to Use
    description                           : Rainy Skies can be used for free, not just a free trial!
    fontawesome_icon_name                 : scale-balanced

  - title                                 : Subscribe for Great Features
    description                           : Get faster refreshes, forecast widgets, and more for $1/month or $5/year (USD)
    fontawesome_icon_name                 : money-bill-1


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                    # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
